services:
   react-app:
     image: react-app:dev
     stdin_open: true
     ports:
        - "5173:5173"
     networks:
        -   mern-app-aichat
   api-server: 
      image: api-server:dev
      ports:
         - "3000:3000"
      networks:
        -   mern-app-aichat         
networks:
    mern-app-aichat:
        driver: bridge